name: lint

on: push

jobs:
  lint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: resolve packages
        run: yarn

      - name: run eslint
        run: yarn lint
